{% set name = "localstack-ext" %}
{% set version = "0.10.128" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b607f34d855f42eb0f345260ef3194355d4b10b084311fbc28b44e6e7d0cfec2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - dnslib
    - dnspython
    - pyaes
    - python

test:
  imports:
    - localstack_ext
    - localstack_ext.bootstrap

about:
  home: https://github.com/localstack/localstack
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Extensions for LocalStack
  doc_url: https://pypi.org/project/localstack-ext/
  dev_url: https://github.com/localstack/localstack

extra:
  recipe-maintainers:
    - mwilson8
    - oblute
    - benhuff
