travis:
  secure:
    BINSTAR_TOKEN: UluBbM/XjC4fvMn9cANpEqB63o1dpjOXEGJ0d/qF7IoP6SUdXnPcZcNAadDP4LsT68GhLNlE6kEZcx79u4OH3jvpjNZ3T38PlB7zFB9XtriHUHLpFA+tWUHOWpk9DJaTx7k/GTjM/M2GLlZxVcryj9i/NQpj9uiAgwUEC+Ic6Si+zxCswSUCs0DhqPN/HGbkpRWyacnNYFRPVvx3169lxSMzTQ/tIcT2YCf8Fi6OZKjKhx2lKi3gdlQc2oW5RwBPhWNjV3A2BculBI532yUMuqnGDVpuvomGWgYLdKju9M6rNPeauyzno/pRzkiF37Hp5YVuXB4U39LX9ITNBwylVowBX8Jqo21Ys2z5HW42takY3pNt7/oBXnPwzynULz8M/Y91EIJ3EWjokjJ3LqyFu7Lnbu/sf7zePGLCsYIck6L+klpUVCIBBOAUqJt6y1gQ2gfGjxwDcQdqtT13TkqTJqBLEX7bowSJURxocm8mI858xxAdRWQknGYvASuDtH6VZOvdUiQA/PnxSemUrBDfUt6KkNoU4US8zhgQuINl5JWJeAbpxlhuwSp82VMgRhnfw6pzBMBA9+RJypm6ZkB7+RVHhGBKH8i9Vr64JL7eegzCk9HhobHCnAwFTC59pwyxg5ZPL25qkuP8F618Fzzayk2f1TLlRsuGfisU17ArXLc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
